#!/bin/bash
PROJDIR=$(cd `dirname $0`/.. && pwd)

TAG=${1}
USER="tomnomnom"
REPO="xtermcolor"

cd ${PROJDIR} && go build github.com/tomnomnom/xtermcolor/cmd/xtermcolor

github-release release \
    --user ${USER} \
    --repo ${REPO} \
    --tag ${TAG} \
    --name "xtermcolor v${TAG}" \
    --description "v${TAG}" \
    --pre-release

github-release upload \
    --user ${USER} \
    --repo ${REPO} \
    --tag ${TAG} \
    --name "linux-amd64-xtermcolor" \
    --file ${PROJDIR}/xtermcolor
